### ISSUE TITLE
total do Mine Relatorio e total conta cartao de credito na tela principal.

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#10]
Caro amigo, de todos os softwares que testei o seu foi o único que consegui me adaptar, só senti falta do valor total das despesas na frente do mine relatório como tinha antes, e você incluir na tela de contas o total de cartão de credito como já tem de poupança e credito aí vai ficar perfeito, o software com essa nova atualização ficou excelente, se mexer estraga a não ser incluir a parte do cartão como eu disse antes. Parabéns, já estava me esquecendo, não teria como você colocar na parte inferior da agenda o total de compras agendada para a gente ter uma ideia de quanto esta devendo?

**Comment by badernageral** [comment]
Olá @abelmuzy, obrigado pelo feedback.
Posso realizar as seguintes mudanças:
- valor total no mini relatório (despesas, receitas e transferências)
- valor total dos itens da agenda (não seria melhor na parte superior?)

Porém não entendi o que quis dizer com o valor total do cartão de crédito, está se referindo ao valor total das despesas agendadas? Se for, o mesmo já é exibido no bloco de despesas agendadas, sob o rótulo "despesas".

**Comment by abelmuzy** [comment]
Boa tarde amigo td bom com vc? o software com o controle de cotas que vc colocou ficou perfeito, mais so temos como controlar as despesas mensal, me referi a cartão de credito da seguinte maneira, vc inclui uma conta cartão de credito na janela de contas ligada a agenda, assim se cadastrar uma conta cartão, toda parcela do cartão da agenda entraria nessa conta cartão e assim saberíamos quanto de limite teríamos nesse cartão para gastar, entendeu? pois a conta cotas ficou perfeita para a gente controlar o quanto podemos gastar no cartão mensal, so faltou temos esse controle anual, tive tentando fazer um jeito de controlar do jeito que esta mais não tive êxito pois não temos como controlar em tempo real as parcelas futuras para sabermos quanto já gastamos no cartão, sobre o mine relatório se vc fizer do jeito que vc falou ficara legal pois já vamos ver logo de cara o quanto já gastamos sem precisar acessar o relatório, obs. se vc conseguir colocar esse controle de cartão em pratica eu lhe pago a parte é só fazer o preço, sei que o software é grátis mais também sei que isso exige muito trabalho, so estou insistindo nessa questão pois o seu software ficou muito fácil de fazer nosso controle financeiro com o sistema de cotas. Parabéns.

**Comment by abelmuzy** [comment]
Boa tarde amigo td bom com vc? o software com o controle de cotas que vc
 colocou ficou perfeito, mais so temos como controlar as despesas 
mensal, me referi a cartão de credito da seguinte maneira, vc inclui uma
 conta cartão de credito na janela de contas ligada a agenda, assim se 
cadastrar uma conta cartão, toda parcela do cartão da agenda entraria 
nessa conta cartão e assim saberíamos quanto de limite teríamos nesse 
cartão para gastar, entendeu? pois a conta cotas ficou perfeita para a 
gente controlar o quanto podemos gastar no cartão mensal, so faltou 
temos esse controle anual, tive tentando fazer um jeito de controlar do 
jeito que esta mais não tive êxito pois não temos como controlar em 
tempo real as parcelas futuras para sabermos quanto já gastamos no 
cartão, sobre o mine relatório se vc fizer do jeito que vc falou ficara 
legal pois já vamos ver logo de cara o quanto já gastamos sem precisar 
acessar o relatório, obs. se vc conseguir colocar esse controle de 
cartão em pratica eu lhe pago a parte é só fazer o preço, sei que o 
software é grátis mais também sei que isso exige muito trabalho, so 
estou insistindo nessa questão pois o seu software ficou muito fácil de 
fazer nosso controle financeiro com o sistema de cotas. Parabéns.

Date: Mon, 1 Feb 2016 07:23:26 -0800

**Comment by badernageral** [comment]
Olá @abelmuzy, quando você fala sobre contas ligadas a agenda, você quer dizer a agenda de lembretes ou as despesas agendadas?
Pelo que entendi você quer uma forma de calcular quanto está sobrando do limite de um cartão de crédito, é isto? e as cotas não servem porque são calculadas somente para o mês atual, é isto?
Um dos propósitos das despesas agendadas é justamente jogar as compras realizadas no cartão de crédito, colocando todas no mesmo dia, fica fácil saber o valor da fatura do mês atual, mas já que você quer saber quanto resta de limite para um cartão de crédito, seria necessário calcular todas as despesas agendadas, pois o limite não considera somente a fatura do mês, mas todas as compras pendentes.
Pensando nisto eu poderia adicionar uma nova aba no mini relatório totalizando as despesas agendadas e adicionando uma flag para separar o que é cartão do que não é.
Porém não acho bom colocar mais um campo para informar o limite do cartão para subtração, pois deixaria o sistema ainda mais complicado.

**Comment by abelmuzy** [comment]
Bom dia amigo, eu me refiro as despesas agendadas, se tivesse como separar por categoria ficaria melhor pois assim a gente tinha como saber quanto ja gastou em um determinado cartao no mes durante o ano, e do jeito que esta nao tem como pois as despesas estao todas misturadas, entendeu? se tivesse como colocar o sistema de cotas para funcionar junto com a agenda ficaria legal tambem, pois se eu fizer uma compra no cartao em 3 veses ja entraria descontando na cota do mes atual e nos 2 meses seguinte, tambem acho que daria certo, mais do jeito que voçe falou ficar melhor pois vai dar menos trabalho para fazer e ao mesmo tempo vai ter como a gente saber nto ja gastou em um determinado cartao.

se voçe achar que vai deixar o software mais lento, faz as modificações so pra mim que eu te pago a parte pois como ja te disse antes, ja testei e comprei vários softwares e so esse que me adaptei melhor, ja fiz uma planilha pra mim, mais planilha é muito vulnerável vira e mexe voçe perde dados.

Date: Tue, 2 Feb 2016 19:25:58 -0800

**Comment by badernageral** [comment]
Olá @abelmuzy, faremos assim:
- vou adicionar setas de navegação no mini relatório, desta forma, será possível navegar pelos meses;
- vou adicionar uma nova aba no mini relatório que agrupará as despesas agendadas por categoria, ou seja, caberá a você categorizar as despesas agendadas, pensei bem e acho melhor não adicionar novas flags, isto deixararia o sistema mais complexo, o que foge da proposta do mesmo que é ser simples;
- adição do valor total no mini relatório (despesas, receitas, transferências e despesas agendadas);
- adição do valor total dos itens da agenda de lembretes;
- também estou construindo um modo de lançamento de despesas/receitas guiado, para ajudar iniciantes;

Não posso cobrar ou fazer uma versão só para você, pois foge do propósito do sistema que é ser livre e acessível para todos, se eu realizar uma alteração, tem que ser para todo mundo.

Desta forma, acho que resolve a maioria dos seus problemas, certo?

**Comment by abelmuzy** [comment]
Legal amigo, e muito gratificante saber que tem pessoas de bom coração assim como você que gosta de ajudar o próximo, coisa que nesse nosso Pais esta raro pois as pessoas só pensa em ganancia só visam o dinheiro. Parabéns.

Date: Wed, 3 Feb 2016 05:21:16 -0800

**Comment by badernageral** [comment]
Olá @abelmuzy, a atualização foi disponibilizada.
Você pode fazer o download [Aqui](https://github.com/badernageral/bgfinancas/releases).

**Comment by abelmuzy** [comment]
Bom dia amigo, ficou muito bom parabéns, agora ja tem como ter uma ideia das despesas do cartao, só que temos de somar todos os meses para chegar ao total gasto no cartao, ficaria melhor ainda se voçe colocar o valor dos totais do mes agendado igual voçe colocou para aparecer acima da despesa, receita e transferencia, colocaria assim, voçe seleciona cartao master aparece acima a despesa desse cartao do mes aí voçe faz como na planilha, cartao master mes janeiro + mes fevereiro ate as ultimas parcelas do cartao, vai me dar o total de gasto desse cartao acima como aparece em despesas entendeu? so que individual aparece em cada despesas que voçe marcar tipo cartao vai me dar o total de compras nesse cartao, cheque predatado vai me dar o total de cheque que tenho para cobrir, nao ficaria perfeito? 
um grande abraço.
Date: Tue, 9 Feb 2016 12:30:05 -0800

**Comment by badernageral** [comment]
Vou colocar um relatório de despesas agendadas, ai você vai poder filtrar por data, isto deve resolver o problema.

**Comment by abelmuzy** [comment]
Caro amigo boa tarde, já tem previsão da correção que você disse que iria fazer no mine relatório para a gente poder saber quanto já gastou em cada categoria?

desculpe, é porque estou curioso para ver como vai ficar, pois como eu ja te disse antes, de todos os software que testei esse é o mais pratico e eficiente.

Date: Wed, 10 Feb 2016 07:31:19 -0800

**Comment by badernageral** [comment]
Olá @abelmuzy, já tinha feito, só estava faltando liberar, você já pode fazer download da versão 3.2.1 que adiciona um relatório para despesas agendadas, neste relatório você poderá filtrar por meses, obtendo assim o valor total agendado por categoria.
Faça o download clicando [aqui](https://github.com/badernageral/bgfinancas/releases).

**Comment by abelmuzy** [comment]
Bom dia amigo, tudo bom com voçe? deixei os softwares que comprei de lado e estou usando so o BGFinanças, mais senti falta de duas coisas, a soma de despesas individual por categoria na tela mine relatorio de despesas agendada e uma conta so para cadastro das despesas do cartao de credito, veja uma foto de como fiz para me adaptar a ele, mais se tiver como voçe colocar em pratica como coloquei tendo uma conta para as despesas do cartao e a soma em mine relatorio por categoria individual de despesas agendadas ficaria melhor.

me desculpe por eu ser tao exigente com um software gratis que voçe nem ganha nada por ele, mais ele ficou tao pratico e facil de usar que esta dando banho nos softwares top que voçe ver por aí.  

From: abelmuzy@hotmail.com
To: reply@reply.github.com
Subject: RE: [bgfinancas] total do Mine Relatorio e total conta cartao de credito na tela principal. (#10)
Date: Wed, 3 Feb 2016 13:38:12 +0000

Legal amigo, e muito gratificante saber que tem pessoas de bom coração assim como você que gosta de ajudar o próximo, coisa que nesse nosso Pais esta raro pois as pessoas só pensa em ganancia só visam o dinheiro. Parabéns.

Date: Wed, 3 Feb 2016 05:21:16 -0800

**Comment by badernageral** [comment]
Olá @abelmuzy, você não anexou a foto, poderia anexar para que eu possa ver?

**Comment by abelmuzy** [comment]
Boa tarde amigo, estranho tenho quase certeza que tinha anexado.

esta na versão Word 2007

Date: Tue, 5 Apr 2016 07:54:40 -0700

**Comment by badernageral** [comment]
Olá @abelmuzy, você está respondendo esta mensagem a partir do seu e-mail? se for, você não conseguirá anexar arquivos, somente respondendo a partir do github. Continuo aguardando seu anexo.

**Comment by abelmuzy** [comment]
Bom dia amigo, eu nao sabia que nao aceitava anexo respondendo por aqui, ja coloquei la na pagina, uma obs. o arquivo foi salvo em word 2007 eu fui abrir no outro pc que esta com word 2013 cortou a imagem, se acontecer isso aí voce me fala que eu te mando em word 2013

muito obrigado pela gentileza.

Date: Wed, 6 Apr 2016 05:52:15 -0700
