### ISSUE TITLE
Atualizaçao do BG Finanças

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#11]
Caro amigo, já tem previsão da correção que você disse que iria fazer no mine relatório para a gente poder saber quanto já gastou em cada categoria?

**Comment by badernageral** [comment]
Olá @abelmuzy, já tinha feito, só estava faltando liberar, você já pode fazer download da versão 3.2.1 que adiciona um relatório para despesas agendadas, neste relatório você poderá filtrar por meses, obtendo assim o valor total agendado por categoria.
Faça o download clicando [aqui](https://github.com/badernageral/bgfinancas/releases).

**Comment by abelmuzy** [comment]
Boa tarde amigo, perfeito agora sim temos como saber quanto ja gastamos em determinado cartao, eu achei que voçe iria colocar essa funçao na tela principal, tipo de acordo que voçe iria avançando os meses iria te dando o montante gasto na categoria que voçe tivesse selecionado na tela de agenda do mine relatorio, tipo despesas que aparece na guia acima do mine relatorio te dar acima o valor total de despesas, achei que voçe iria fazer desse jeito individual por categoria, mais depois vi que iria ser mais trabalhoso fazer assim.

ficou muito bom, eu tenho softwares que ja te dar a fatura do cartao ja fechada, ou seja ja separa a fatura de acordo com sua data de fechamento e vencimento, mais sao meio confusos na hora de fazer a contabilidade das contas. 

o BG Finanças é mais simples e seguro do que uma planilha pois a planilha voçe coloca do seu jeito mais de vez em quando aparece um erro no excel e voçe nao consegue fazer nada, por isso prefiro um software compilado pois nao temos esses erros bobos.
Parabéns.

Date: Sun, 6 Mar 2016 18:22:09 -0800
