### ISSUE TITLE
Conta Cartao de Credito

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#12]
Caro amigo estou enviando a foto por aqui pois nao estava conseguindo pelo meu e-mail.
[Veja amigo como eu fiz para poder controlar os gastos dos meus cartões.docx](https://github.com/badernageral/bgfinancas/files/206570/Veja.amigo.como.eu.fiz.para.poder.controlar.os.gastos.dos.meus.cartoes.docx)

sao valores fiquiticios so para voçe ter uma ideia, veja como ficou legal as faturas em mine relatorio

**Comment by badernageral** [comment]
Final de semana lhe dou uma resposta, vou pensar um pouco.

**Comment by abelmuzy** [comment]
Bom dia amigo, tudo bem, se você usa o software vai perceber que vai ficar bem mais fácil para a gente controlar nossas despesas com cartão.

um grande abraço.

Date: Thu, 7 Apr 2016 06:46:51 -0700

**Comment by abelmuzy** [comment]
Boa noite amigo, eu tive analisando se voçe fizer uma conta para ir somando os gastos em cada cartao nao precisa mexer no mine relatorio para colocar a soma das categorias, pois na conta do cartao ja vai aparecer pra gente o total gastos em cada cartao, certo?

From: abelmuzy@hotmail.com
To: reply@reply.github.com
Subject: RE: [badernageral/bgfinancas] Conta Cartao de Credito (#12)
Date: Thu, 7 Apr 2016 14:30:41 +0000

Bom dia amigo, tudo bem, se você usa o software vai perceber que vai ficar bem mais fácil para a gente controlar nossas despesas com cartão.

um grande abraço.

Date: Thu, 7 Apr 2016 06:46:51 -0700

**Comment by badernageral** [comment]
Olá @abelmuzy, implementei um sistema de cartões de crédito, você verá que agora tem um novo botão para cadastrar cartões de crédito. 
Ao cadastrar uma despesa agendada, você pode vincular a despesa a um cartão. 
Na área de cartões ele exibe quanto ainda resta de limite no cartão. 
O relatório de despesas agendadas agora também permite filtrar por cartão de crédito e os outros por conta.
Você pode baixar clicando [aqui](https://github.com/badernageral/bgfinancas/releases).
