### ISSUE TITLE
Sugestao

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#13]
Bom dia amigo, veja essa tela de lançamento para você ter uma ideia.
[tela de lançamentos.docx](https://github.com/badernageral/bgfinancas/files/219183/tela.de.lancamentos.docx)

**Comment by badernageral** [comment]
Esta tela que você mandou me deu uma idéia, vou criar um sistema de grupos para as despesas, isso deve resolver seu problema, pois listarei para cada grupo o valor pago e o a pagar, só estou precisando de tempo, deve demorar um pouco para eu fazer a atualização.

**Comment by abelmuzy** [comment]
Perfeito amigo, você vai ver que o BGFinanças vai ficar melhor do que todos que a gente ver por aí pago, pois o BGFinanças e leve não ocupa espaço e fácil de entender e tem ainda a facilidade de fazer backup e restauração.

um grande abraço.

Date: Thu, 14 Apr 2016 07:07:10 -0700

**Comment by badernageral** [comment]
Olá @abelmuzy, implementei um sistema de cartões de crédito, você verá que agora tem um novo botão para cadastrar cartões de crédito. 
Ao cadastrar uma despesa agendada, você pode vincular a despesa a um cartão. 
Na área de cartões ele exibe quanto ainda resta de limite no cartão. 
O relatório de despesas agendadas agora também permite filtrar por cartão de crédito e os outros por conta.
Você pode baixar clicando [aqui](https://github.com/badernageral/bgfinancas/releases).
