### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by felipedash** [badernageral/bgfinancas#14]
Olá, eu gostaria de agradecer pelo seu programa, está ajudando muito minha família! 
Tem algumas coisas que gostaria de ver nele para ficar mais perfeito:
1 - Uma forma de criar um usuário para mim e minha esposa;
Que fique separada das minha finanças, quando eu crio um usuário, é só uma senha diferente para entrar no mesmo login.
2 - Ter um relatório separado entre as contas;
Tipo, se não for possível ter login separado, queria poder saber quanto cada conta minha está gastando em um "SuperMercado", separadamente.

Até agora, apenas isso que eu senti dificuldade! 
Muito bom, obrigado!

**Comment by badernageral** [comment]
Olá @felipedash, obrigado pelo feedback.
1 - Já havia pensado em tornar o sistema multi-usuário, porém é uma modificação muito grande que demandaria muito tempo, e atualmente estou com pouco. Você poderia instalar 2 cópias do sistema e assim ter finanças diferentes, porém os itens e categorias não seriam compartilhados, o que torna a operação um tanto inviável.
2 - Criar um filtro por conta nos relatórios é muito fácil, se isso resolver o seu problema, posso implementar este final de semana.

**Comment by felipedash** [comment]
Sim isso já me ajudaria muito. Obrigado pelo seu tempo e seu trabalho!
Eu estou estudando programação, sei o quanto da trabalho esse sistema! 
Agradeço desde já, o que eu encontrar que possa ajudar para que melhore seu sistema eu lhe avisarei! Abraço!

**Comment by badernageral** [comment]
Olá @felipedash, coloquei o filtro por conta nos relatórios, também implementei um sistema de cartão de crédito nas despesas agendadas.
Você pode baixar clicando [aqui](https://github.com/badernageral/bgfinancas/releases).

**Comment by felipedash** [comment]
Irmão! Obrigado, você realmente mostrou a que veio, está perfeito!
Agora consigo visualizar as coisas direitinho.
Só tem umas coisa, é boba, mas pode ser que você até já tenha pensado nisso.
Quando eu uso o programa em conjunto com o java, não consigo colocar ele como atalho na barra
de inicialização rápida!

**Comment by badernageral** [comment]
Olá @felipedash, havia percebido, só não tinha dado atenção, mas agora que você falou, realmente é um problema, o programa é visto como se fosse a maquina virtual, vou atribuir um ID de aplicação e deve resolver. Também percebi que um dos relatórios (despesas por tempo) não está funcionando o filtro por conta, vou aproveitar e corrigir, porém só vou colocar a nova versão no meio da semana. Se tiver mais alguma sugestão, diga ai que já implemento.

**Comment by felipedash** [comment]
Ok, cara quando a gente clica em sobre o sistema, aparece o desenvolvedor, você no caso, e o site, mas seria mais legal se foce um link direto pro site e não apenas texto.
Outra coisa era em despesas por tempo tbm, seria legal acompanhar as despesas por semana, por mês e por ano, assim podemos analisar mais, tipo eu assim que comecei a cadastrar minhas despesas, tive que esperar passar um mês pra ver essa função funcionando...
Mais uma vez, muito obrigado pela sua atenção...

**Comment by badernageral** [comment]
Você está falando do relatório de despesas por tempo?

**Comment by felipedash** [comment]
sim

**Comment by badernageral** [comment]
Blz, vou colocar uma opção: "mensal", "semanal" e "anual".

**Comment by felipedash** [comment]
Obrigado irmão! abraço! qualquer coisa eu te falo! :+1:

**Comment by badernageral** [comment]
Olá @felipedash, realizei quase todas as implementações que você pediu, somente a do ícone na barra de tarefas que não foi realizada, você pode conferir clicando [aqui](https://github.com/badernageral/bgfinancas/releases).
Para fixar o ícone na barra de tarefas (Windows 7 em diante), o Windows limita ao software que está executando, como o BG FInanças é um programa escrito em Java, ele só identifica a JVM e não permite colocar um atalho para o .jar do aplicativo.
Para resolver isto eu poderia utilizar um wrapper e gerar um exe, porém ao realizar testes, vi que algumas versões podem gerar problemas, então decidi não implementar pelo risco de haver problemas com alguns usuários. Também é possível gerar um atalho apontando para o cmd do Windows, porém a janela do cmd fica aberta por 1 segundo, então preferi não disponibilizar este atalho junto do programa, mas caso tenha interesse, clique [aqui](http://superuser.com/questions/257467/windows-7-how-to-pin-a-jar-to-the-taskbar).
Qualquer sugestão sempre é bem vinda, obrigado pelo feedback.

**Comment by felipedash** [comment]
Cara ficou muito bom, obrigado, qualquer coisa entro em contato, abraço!
