### ISSUE TITLE
Cartao de Credito

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#15]
**Perfeito amigo, exatamente isso, só vou ter de cadastrar todas as minhas faturas de novo kkkk, pois vi que não tem como editar elas, mais vai valer o esforço pois agora a gente vai ter como controlar as compras com cartão e não estourar o orçamento, você optou em não colocar o dia de fechamento da fatura né, mais se a gente prestar atenção na hora de comprar é só ver o dia que fecha e colocar para o mês seguinte certo? parabéns agora sim ficou show de bola.

vi que um amigo pediu para você colocar uma opção de usuário independente e relatório com categoria separada mais eu acho que o software já faz isso certo, apesar de só eu que uso ele aí não tive a curiosidade de criar outro usuário. um grande abraço.**

**Comment by badernageral** [comment]
Olá @abelmuzy, desculpe não colocar para alterar, foi o tempo, vou colocar mais para frente.
Não tinha pensado no dia de fechamento da fatura, vou implementar depois.
Apesar do sistema permitir mais de um usuário, os usuários compartilham as finanças, ou seja, não é multi-usuário.

**Comment by abelmuzy** [comment]
Boa noite amigo, estou refazendo todo o cadastro das minhas compras no cartao aqui e ficou shou de bola.

coloquei em categoria

fatura cartao credicard master

coloquei em cartao de credito

credicard master abel
credicard master rose adcional da minha esposa

aí quando vou cadastrar as compras eu seleciono o cartao se foi feito a compra no meu master ou no dela cai na mesma fatura credicard master, entendeu?

assim ficou show de bola, se voçe poder colocar a data de fechamento da fatura sem mexer do jeito que voçe fez seria bom, do jeito que voçe fez nao precisa de data de fechamento pois quando voçe seleciona o cartao ja entra a data, se voçe colocar a data de fechamento vai ter de colocar a data de compra e data de vencimento ou nao colocar ela vinculada ao cartao, se eu fosse voçe deixaria assim mesmo, pois é só memorizar o dia que o cartao vence tipo vence dia 25 para vim na fatura do mes seguinte é só comprar depois do dia 15 certo? se nao der muito trabalho né e poder incluir nunca é demais.

um grande abraço.

Date: Sun, 1 May 2016 05:09:35 -0700
