### ISSUE TITLE
Uma sugestao e um possivel erro que encontrei

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#16]
Bom dia amigo, hoje eu fui dar baixa em umas despesas e notei que não estão sendo descontadas nas cotas, será erro no software ou eu que fiz algo errado pois antes da atualização estava normal.
sobre a sugestão é o seguinte:
seria bom que você colocasse a soma das contas em lembretes só as contas atrasadas e vencendo no dia pois assim a gente já ficava sabendo quanto de debito esta pendente, entendeu?
só isso, o modo que você colocou para fazer o cadastro das despesas de cartão ficou perfeito, eu ainda não tinha visto um modo simples e tão eficiente , parabéns pela excelente ideia.

**Comment by badernageral** [comment]
Olá @abelmuzy, não encontrei erro nas cotas, será que você não percebeu errado? verifique novamente, faça testes e me dê mais detalhes para que eu possa encontrar o erro.
Os lembretes de contas vencendo no dia, o sistema já avisa caso seja uma despesa agendada. O foco do módulo de lembretes é adicionar alguma coisa que você não adicionaria em despesas agendadas. Como por exemplo contas a receber. O valor total somente para o que está vencendo vai ficar confuso. Como você está usando este módulo?
O módulo de cartões ainda vou melhorar um pouco, mas obrigado pelo feedback.

**Comment by abelmuzy** [comment]
Bom dia amigo, sobre as cotas, antes de atualizar o sistema eu dava baixa em uma conta era descontado na cota, agora nao acontece nada ou seja nao esta descontando, e eu fiz cadastro igual estava antes, quando voçe paga uma conta automaticamente nao é descontado na cota? entao: isso nao esta acontecendo mais.sobre a agenda de lembretes eu só citei esta sugestao pois eu estou cadastrando todas as minhas contas nele aí a soma acima ja me dava o que tenho de pagar de atrasado e do dia de vencimento.referente ao aviso que voçe falou que tem só aparece na hora que voçe abre o software, a nao ser na janela de contas agendadas que te dar uma ideia tambem das contas vencendo, só mencionei a agenda de lembretes pois me dava acima o total de contas pendente, mais concordo com voçe, a gente deve deixar a agenda de lembretes só para contas a receber recados e aniversarios.a parte de cartao ficou perfeito da maneira que voçe fez se poder incluir a data de fechamento das fatura sem mexer na tela de lançamentos seria bom pois do jeito que voçe fez ficou show pois posso incluir compras de cartoes diferente na mesma fatura. outra coisa que observei o cadastro das compras no cartao depois de incluir todas, o limite nao esta batendo.faz um teste aí, pode ser um erro da operadora tambem será? ou comi mosca nessa tambem  kkkk
um grande abraço. 
Date: Fri, 6 May 2016 12:51:49 -0700

**Comment by badernageral** [comment]
Olá @abelmuzy, voltei a ativa e disponibilizei uma nova versão, confira clicando [aqui](https://github.com/badernageral/bgfinancas/releases).
Uma das alterações é permitir alterar o cartão de crédito, como você tinha pedido.
Você tem certeza que as cotas não estão sendo descontadas? Ao cadastrar a cota você atribuiu as categorias de despesa? Talvez você só tenha cadastrado a cota e esquecido de atribuir as categorias.
Quanto ao limite do cartão, está tudo certo, eu calculo assim: somo o valor de todas as despesas agendadas não efetivadas que estão atribuídas aquele cartão, depois subtraio este valor do limite e exibo o limite restante. Fiz os cálculos manualmente e está funcionando. Talvez você não cadastrou alguma compra que não tenha entrado em suas faturas ainda, por isso a diferença.
Aguardo resposta.
