### ISSUE TITLE
Cota de Despesas

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#17]
Boa tarde amigo, Parabéns a cada dia o BG Finanças fica mais perfeito, sobre as cotas voçe tinha razao eu nao tinha atribuido algumas categorias por isso nao estava sendo descontadas, uma pequena sugestao para a proxima atualizaçao, em despesas agendadas voçe colocou filtro para despesas sem cartao e todos, na proxima atualizaçao voçe coloca todos os cartoes pois vai ficar mais facil a gente saber o total de gastos com todos o cartoes, principalmente para alguem como eu que tenho 5 cartoes e nao vamos precisar somar o total de um a um, notei tambem que nao esta aceitando alterar o saldo das contas mais, isso seria importante, pois eu tenho PIC itau e todo meu eu altero o saldo, fui fazer isso agora nao permitiu eu alterar mais, só se fizer uma especie de inclusao de rendimentos para podeu reajustar agora, foi voçe que bloqueou as alteraçoes de saldo das contas ou é um bug?

**Comment by badernageral** [comment]
Olá @abelmuzy, depois coloco essa opção de filtro.
Quanto a alterar o saldo das contas, está funcionando perfeitamente aqui, tente fazer em mais de uma conta, para ver se é um bug.
