### ISSUE TITLE
Uma ideia sobre inicializar junto do windows

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#18]
Caro amigo tive pensando em uma opçao mais facil ja que colocar ele iniciar junto do windows seria mais complicado, a opçao é a seguinte: voçe colocar opçao para cadastrar o login na hora que instala ele opcional, ou seja instalar sem cadastrar senha para ele abrir direto, pois eu tenho o Jfinanças que tem essa opçao eu abro ele direto sem efetuar login, assim se eu colocar ele no menu iniciar ele vai abrir direto junto com o windows entendeu? 

veja esse link é sobre iniciar programa em java junto do windows
http://translate.google.com/translate?hl=pt&sl=auto&tl=pt&u=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F7490249%2Finno-setup-how-can-i-make-my-program-run-when-a-user-logs-in-to-windows  
esta traduzido em baixo esta o link original

http://www.guj.com.br/t/como-iniciar-programa-junto-com-windows-resolvido/139413/9
e so clicar aqui
http://stackoverflow.com/questions/7490249/inno-setup-how-can-i-make-my-program-run-when-a-user-logs-in-to-windows

**Comment by badernageral** [comment]
Vamos ver se eu entendi, você quer abrir o programa sem ter que digitar usuário e senha? Se for o caso, posso adicionar uma configuração que desative o login, dentro do programa, não no instalador.
Iniciar junto com o Windows é só colocar o atalho do programa na pasta Inicializar do menu iniciar.

**Comment by abelmuzy** [comment]
Exatamente isso amigo, pois assim eu colocando ele no menu iniciar quando eu ligar o notebook ele ja abre direto e eu nao esqueço de ver se tem contas vencendo no dia.
