### ISSUE TITLE
Saldo das Contas

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#19]
Caro amigo, continua com o probrema, nao esta aceitando eu alterar os saldos das contas, voçe entra em editar aceita voçe mudar o valor mais na hora que voçe clica em alterar nao altera.

**Comment by badernageral** [comment]
Olá @abelmuzy, fiz vários testes e ainda assim deu tudo certo, precisaria de mais dados, faça assim, abra o arquivo banco.script que se encontra na pasta do programa com um editor de textos, procure as linhas relativas as contas, conforme exemplos abaixo:

```
INSERT INTO CONTAS VALUES(0,'Banco',500.00,1,'0')
INSERT INTO CONTAS VALUES(1,'Carteira',233.00,1,'0')
INSERT INTO CONTAS VALUES(2,'Poupan\u00e7a',200.00,1,'1')
```

Poste elas aqui ou envie para meu e-mail (clique no minha imagem e veja no meu perfil).
Outra coisa, não crie mais issues, responda neste, pois há muitos tópicos.

**Comment by abelmuzy** [comment]
Bom dia, mandei em anexo, se nao chegou aí me manda o seu e-mail pessoal que te mando.

**Comment by abelmuzy** [comment]
mandei compactado

**Comment by badernageral** [comment]
Olá @abelmuzy, os dados estão normais, consegui alterar normalmente aqui, faça isso:
- Veja qual a versão do Java instalado no seu computador e poste aqui.
- Se estiver desatualizado, atualize-o e faça testes novamente.
- Faça backup dos seus dados, instale o programa em outro computador, importe o backup e veja se funciona.

**Comment by abelmuzy** [comment]
Boa tarde amigo, resolvido o problema, era o java mesmo, atualizei resolveu, estranho que com a versão 3.3 estava funcionando normal.
um grande abraço.

**Comment by abelmuzy** [comment]
Fui incluir um compromisso com valor negativo tipo -200,00 para ficar em vermelho para me chamar atenção e não esquecer não aceita mais, você tirou essa opção?

**Comment by badernageral** [comment]
Olá @abelmuzy, também achei estranho ser a versão do Java, a minha está desatualizada aqui e funciona. Vai ficar como mistério haha XD
Sobre o valor negativo, é um bug da última versão.
Como implementei a possibilidade de você informar valores como:
- 4+4
- 3*6
- 5-3
- 5/4

O programa calcula o valor para você, porém ao informar um valor negativo, -200, ele pensa que é um calculo e acaba gerando um erro. Vou resolver no próximo update.

**Comment by abelmuzy** [comment]
Olá amigo td bom com voçê?


tentei enviar uma mensagem lá pelo site nao consegui, baixei a nova versao ficou legal com o extrato agora, eu iria te dar essa ideia tambem mais nao cheguei a falar pois voçe tinha me dito que nao queria acrescentar muita coisa no software por se tratar de um software simples e objetivo, ja que voçe colocou a tela de extrato vou de dar mais uma dica, seria colocar a soma das despesas na parte inferior para ficar mais facil para a gente saber quanto ja gastou.

outra coisa que observei foi o seguinte.

nao esta filtrando as despesas por status. tipo: voçe seleciona banco itau e so te dar as contas que foram pagas no itau entendeu?


ficaria legal se voçe colocasse a soma na parte inferior das despesa e da receita para a gente saber quanto pagou e quanto gastou em cada conta.


outro detalhe que acho que ja falei com voçe e de colocar uma opçao de selecionar todas as contas da fatura do cartao para pagar de uma so vez em vez de ficar pagando uma a uma pois eu que tenho varias compras sabe o tempão que leva dando baixa.


um grande abraço e muita saúde e sucesso para voçe e sua familia em 2017

________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: domingo, 25 de setembro de 2016 21:38:52
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Saldo das Contas (#19)


Closed #19<https://github.com/badernageral/bgfinancas/issues/19>.

-

**Comment by badernageral** [comment]
Olá @abelmuzy, quanto tempo, realmente esqueci de colocar o total no extrato, erro meu, vou colocar na próxima atualização.
Sobre a baixa múltipla de contas, eu acabei esquecendo nesta atualização, é uma boa ideia, vou implementar também.
Já o filtro, se você digitar o nome da conta, ou o valor, ele vai filtrar, faça um teste.
Qualquer coisa, você me acha por aqui. XD

**Comment by abelmuzy** [comment]
Boa noite amigo, realmente fiquei um tempo sem postar mensagem, quem manda você deixar o BGFinanças com essa perfeição  kkk para você ter uma ideia já comprei mais de 10 softwares e o único que esta me ajudando nas minha finanças é o BGFinanças pois os outros são muito complicado de você chegar a uma conclusão geral de suas despesas e receitas.


para você ter uma ideia o BGFinanças é o único que você pode ter um cartão de credito adicional e ele te mostra a fatura em uma só, os outros software não faz isso só te mostra a fatura separada.


tipo: o meu cartão a fatura veio 650,00 o da minha esposa que e adicional veio 450,00 o total da fatura que aparece na tela de agendamento e 1100,00 certo? nos outros software não faz isso te mostra as faturas separada e você tem de somar para saber o valor total da fatura, nesse quesito você deu um banho de conhecimento nos desenvolvedores de softwares top que a gente conhece por aí, Parabéns pelo excelente trabalho.


mais pra frente se você achar que seja interessante colocar uma importação de extrato bancário aí sim adeus para os outros softwares.


uma grande abraço.


________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: terça-feira, 10 de janeiro de 2017 21:54
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Saldo das Contas (#19)


Olá @abelmuzy<https://github.com/abelmuzy>, quanto tempo, realmente esqueci de colocar o total no extrato, erro meu, vou colocar na próxima atualização.
Sobre a baixa múltipla de contas, eu acabei esquecendo nesta atualização, é uma boa ideia, vou implementar também.
Já o filtro, se você digitar o nome da conta, ou o valor, ele vai filtrar, faça um teste.
Qualquer coisa, você me acha por aqui. XD

-

**Comment by badernageral** [comment]
Eu já tinha considerado importar extrato, porém não tem como eu relacionar os itens do extrato com as despesas cadastradas, pois pode ser qualquer coisa, e algumas até na verdade seriam compostas (por exemplo, no extrato uma compra em uma loja poderia ser na verdade vários itens), resumindo, uma bagunça, por que o sistema trabalha com despesas pré-cadastradas para facilitar o controle, desta forma, resolvi deixar de lado a ideia.

**Comment by abelmuzy** [comment]
Entendi amigo, nao teria como voçe colocar a opçao de editar as categorias?

digo isso pois eu tenho uns softwares aqui que tem essa opçao.


veja essa tela de extrato de um deles.

________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: quarta-feira, 11 de janeiro de 2017 02:31:05
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Saldo das Contas (#19)


Eu já tinha considerado importar extrato, porém não tem como eu relacionar os itens do extrato com as despesas cadastradas, pois pode ser qualquer coisa, e algumas até na verdade seriam compostas (por exemplo, no extrato uma compra em uma loja poderia ser na verdade vários itens), resumindo, uma bagunça, por que o sistema trabalha com despesas pré-cadastradas para facilitar o controle, desta forma, resolvi deixar de lado a ideia.

-

**Comment by badernageral** [comment]
Para editar as categorias clique no botão de despesas, nesta tela onde exibe as despesas, observe que há um botão ao lado do combo onde você pode selecionar e filtrar por categoria, clicando nele você verá todas as categorias, permitindo altera-las.
