### ISSUE TITLE
Acesso Banco de Dados

### ISSUE THREAD

**Issue by Kleydson** [badernageral/bgfinancas#20]
É possível acessar o banco de dados através de algum programa?

**Comment by badernageral** [comment]
Olá @Kleydson, desculpe a demora a responder.
O banco utilizado pelo sistema é o HSQLDB, você pode usar o DbVisualizer que pode ser encontrado neste [link](https://www.dbvis.com/download). Como o procedimento não é muito intuitivo, veja este [tutorial](https://confluence.atlassian.com/conf57/connecting-to-hsqldb-using-dbvisualizer-or-hsql-database-manager-701435605.html).
O driver utilizado no DbVisualizer pode ser encontrado na pasta lib dentro do diretório do BG Finanças.
Qualquer dúvida estou por aqui.
