### ISSUE TITLE
Total de despesas do cartao nao esta conferindo com o mine relatorio

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#21]
Bom dia amigo, fiz uns estorno de compras com cartao, colocando o sinal - antes do valor claro estou usando a versao 3.3 só que na soma das compras do cartao esta um valor e no quadro mine relatorio esta outro valor esta somando pra menos, o que pode esta acontecendo? voçe tinha me dito que iria corrigir esse detalhe de nao poder incluir o sinal de menos na versap 3.4, voçe ja corrigil?

**Comment by badernageral** [comment]
Olá @abelmuzy, quando você diz estorno de compras, você lançou uma despesa com sinal negativo? na versão 3.4 não é possível lançar uma despesa com sinal negativo.
Se eu compreendi bem, o correto seria excluir a compra em vez de lançar outra compra com sinal negativo.
Recomendo que você exclua a despesa com valor negativo e atualize para a versão 3.4.
Se não der certo me avise.

**Comment by abelmuzy** [comment]
Boa dia amigo, entendi o que vc disse porem eu prefiro a versao 3.3 pois com a opçao de colocar o sinal - antes do valor eu tenho como colocar exatamente como esta na fatura e em lembretes de vencimentos das contas o sinal - é importante para chamar a atençao que temos contas em atraso.
vc tinha me dito que iria colocar a opçao de entrar direto no menu do BGFinanças sem precisar fazer login para a gente poder colocar ele no menu iniciar e ja abrir a tela te mostrando os afazeres do dia e corrigir esse detalhe do sinal de menos, vc mudou de ideia?
outra coisa que eu te pedi para colocar e vc disse que em uma nova atualizaçao iria corrigir é colocar na tela de movimentaçao dos cartoes a soma geral para a gente poder saber quanto ja gastou no mes com todos os cartoes, vc esqueceu?

**Comment by badernageral** [comment]
Olá @abelmuzy, realmente tinha esquecido, tinha dito que ia permitir o lançamento negativo e fui ver nas minhas anotações e tava aqui, vou realizar estas alterações, até a semana que vem devo terminar e te aviso.

**Comment by badernageral** [comment]
Olá @abelmuzy, realizei as modificações que conversamos e mais algumas, você pode fazer download na área de [releases](https://github.com/badernageral/bgfinancas/releases).

**Comment by abelmuzy** [comment]
Boa noite amigo, ficou muito bom parabéns, só notei uma pequena coisa, fui cadastrar uma compra em um cartão que vence agora dia 25/09 e quando eu selecionei ele em vez dele mudar a data para 25/10 permaneceu na data de hoje, você tinha percebido isso? eu não tinha observado, eu fiz um cadastro na fatura de outro cartão que vence dia 02/10 ele mudou da data de hoje para o dia 02/10 não teria de ter mudado para 02/11 já que todo cartão fecha 10  dias antes da data de vencimento da fatura?

só notei esse detalhe, no mais ficou show, sendo que esse detalhe da data não chega a atrapalhar e só a gente ver se já tem menos de 10 dias para a fatura vencer, mais se na próxima atualização for possível corrigir esse detalhe vai ficar perfeito.

um grande abraço.

---

De: José Robson Mariano Alves notifications@github.com
Enviado: domingo, 25 de setembro de 2016 22:15:05
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Total de despesas do cartao nao esta conferindo com o mine relatorio (#21)

Olá @abelmuzyhttps://github.com/abelmuzy, realizei as modificações que conversamos e algumas outras, você pode fazer download na área de releaseshttps://github.com/badernageral/bgfinancas/releases.

##

**Comment by badernageral** [comment]
Vou anotar para a próxima. :-D

**Comment by abelmuzy** [comment]
Bom dia amigo, ja estou exigente de mais kkk aproveita na próxima atualização ver se tem como voçe colocar para pagar as despesas do cartão tudo de uma vez, pois do jeito que voçe fez a gente tem de dar baixa uma a uma e eu que compro muita coisa tenho as vezes que dar baixa em mais de 20 compras isso só em um cartão. dar uma olhada nesse software VBA para voçe ter uma ideia.

http://www.logsoft.com.br/download.asp
