### ISSUE TITLE
Edição de categoria

### ISSUE THREAD

**Issue by diegogiacomo** [badernageral/bgfinancas#22]
Boa noite!

Minha dúvida é referente a edição ou exclusão de categoria (Despesas/Itens/Categoria), isso na versão BG Finanças 3.4. Por padrão já vem uma categoria "Carro" e gostaria de mudar para "Transportes".

**Comment by badernageral** [comment]
Olá @diegogiacomo, você pode alterar ou excluir a categoria, basta ir a área de categorias de despesas.
O procedimento é o seguinte: clique no ícone de despesas, em cima, ao lado dos botões de cadastrar/alterar/excluir, há um filtro por categoria, do lado desse filtro há um ícone com uma pasta, basta clicar nele. Depois clique duas vezes na categoria desejada e altere-a.
