### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by mr-tcan** [badernageral/bgfinancas#23]
There is a way to recover a lost password?

PS.: I do not use the program, a friend of mine does.

**Comment by badernageral** [comment]
Olá Thiago, vi que você é brasileiro, vou falar em português XD
Se seu amigo esqueceu a senha, basta altera-la diretamente no banco de dados.
Para isto abra o arquivo "banco.script" que está localizado na pasta de instalação do sistema.
Procure por uma linha como a que está abaixo:

> INSERT INTO USUARIOS VALUES(0,'nome','usuario','698dc19d489c4e4db73e28a713eab07b')

Acredito que você tenha conhecimento sobre SQL, o terceiro e quarto parâmetros são o nome do usuário e a senha, respectivamente. A senha é criptografada em MD5, você pode alterar para esta mesma do exemplo, que corresponde a palavra "teste".
Depois salve o arquivo e abra o sistema novamente.
Devo frisar que se você acessar o menu "Utilitários" > "Configurações", há a opção para desativar o login no sistema, o que pode facilitar a vida de seu amigo.
Espero ter ajudado.

**Comment by mr-tcan** [comment]
Valeu José.
Vou fazer a alteração e testar.
Abraço.
