### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by wilkdomim** [badernageral/bgfinancas#24]
Esse programa é ótimo! Muito melhor que minha planilha excel! hehe
Gostaria de no fim de cada mês gerar um extrato (pdf, bloco de notas, no que der menos trabalho para vc) no qual fosse possível visualizar as receitas e despesas por dia, como um extrato de movimentações de conta corrente (últimos lançamentos).
Vi no site softdownload um comentário onde outro senhor também buscou por isso.
http://www.softdownload.com.br/controle-despesas-windows-bg-financas.html

É muito complicado implementar essa opção de impressão? Ou já existe e eu que não consegui achar? kkk
Pelo que vi parece que você é o único a implementar o código, agradeço por sua dedicação.

**Comment by badernageral** [comment]
Olá @wilkdomim, realmente não há um relatório para itens individuais, seria uma lista com os itens organizados de forma crescente por data?
Estou planejando uma atualização para o natal e posso incluir sua sugestão.

**Comment by wilkdomim** [comment]
Isso mesmo, uma lista que mostre a movimentação dos gastos ao longo do tempo.
As atualizações são sempre postadas neste site?

**Comment by badernageral** [comment]
As atualizações são postadas aqui neste site.
Você quer a movimentação dos gastos ao longo do tempo? existe um relatório que mostra a movimentação ao longo do tempo por mês e categorias.
O relatório seria isto diariamente por categoria (agrupado) ou somente uma lista dos itens?
Se você fizer um esboço fica mais fácil.

**Comment by wilkdomim** [comment]
Eu estava pensando em apenas uma lista geral com todas as receitas e gastos que temos, independente de terem sido pagas pela carteira, crédito, débito...
Um resumo de tal data até tal data.
Fiz um esboço como você pediu, veja o que acha.
[EXTRADO BG.pdf](https://github.com/badernageral/bgfinancas/files/662193/EXTRADO.BG.pdf)

**Comment by badernageral** [comment]
Entendi, quando tiver implementado te aviso por aqui. XD

**Comment by badernageral** [comment]
Olá @wilkdomim, acabei colocando 2 novos relatórios, uma lista com as despesas e um extrato, mais ou menos como você pediu, de uma olhada (clicando [aqui](https://github.com/badernageral/bgfinancas/releases/tag/3.6)), além de outras melhorias no sistema.
Mais para frente vou implementar um botão para impressão nos relatórios.
Aguardo feedback.

**Comment by wilkdomim** [comment]
Ficou bem completo o extrato, importei meus dados e ficou melhor do que eu pensei! Já me familiarizei com o programa e uso quase todos os dias.
Valeu mesmo @badernageral! 
=D

**Comment by badernageral** [comment]
Obrigado pelo feedback, se achar algum bug ou tiver novas sugestões, você já sabe onde falar XD

**Comment by abelmuzy** [comment]
Boa tarde amigo td bom com você? Então, não sei se já te falei mais em relatório no modo extrato, faltou você colocar para filtrar as contas individuais e aparecer em baixo na barra inferior o total de credito e total de debito de cada conta, isso iria facilitar para a gente saber o movimento mensal bancário por exemplo, quanto entrou e quanto saiu da conta, se tivesse como você colocar a função para importar os extratos no modo ofx ficaria mais perfeito ainda. um grande abraço.

Ass. Abel.

**Comment by badernageral** [comment]
Olá @abelmuzy, realmente, não está filtrando por conta, é um bug, irei corrigir e colocar os totais embaixo, deve demorar um pouco porque estou ocupado com estudos, mas farei. Quanto a essa importação de extratos já havia explicado em um tópico que devido as despesas serem pré-cadastradas não haveria como fazer esta importação.

**Comment by abelmuzy** [comment]
Bom dia amigo, tudo bom com voçe? recebi um link de um comentario de usuario do BGFinanças e me lembrei de comentar com voçe a respeito sobre o extrato de contas, em relatorio quando voçe for fazer atualizaçao no BGFinanças, seria bom voçe colocar para filtrar os extrato de contas individual com o os valores em baixo do credito debito e saldo das contas, o que voçe acha nao ficaria legal?


um grande abraço.


________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: quarta-feira, 30 de agosto de 2017 21:25
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Sugestão (#24)


Reopened #24<https://github.com/badernageral/bgfinancas/issues/24>.

**Comment by badernageral** [comment]
Estou modificando o extrato, devo soltar uma atualização até o final de semana, só não entendi direito o que você quis dizer, vou colocar os valores totais de crédito e débito no relatório.

**Comment by abelmuzy** [comment]
Eu me referi sobre mostrar as somas do total de credito, despesas e saldo no rodapé do formulário, para quando voçe selecionar uma conta voçe saber quanto entrou e quanto saiu e o saldo daquela conta, entendeu?

________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: quinta-feira, 31 de agosto de 2017 14:29:00
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Sugestão (#24)


Estou modificando o extrato, devo soltar uma atualização até o final de semana, só não entendi direito o que você quis dizer, vou colocar os valores totais de crédito e débito no relatório.

**Comment by badernageral** [comment]
Não irei mostrar o saldo (pois ele não irá refletir a verdade devido a possibilidade de haver transferências), mas irei mostrar os totais. Quando postar a atualização lhe aviso por aqui.

**Comment by badernageral** [comment]
Olá @abelmuzy, uma atualização foi postada.
Você pode fazer download [aqui](https://github.com/badernageral/bgfinancas/releases).
