### ISSUE TITLE
BG Finanças Instalação

### ISSUE THREAD

**Issue by marcelokalef** [badernageral/bgfinancas#25]
Estou tentando instalar o programa no Windows 8.  Aparece a mensagem pedindo para baixar e instalar o Java, mas mesmo depois do Java instalado continua aparecendo a mensagem e a instalação não inicia. 
Alguma dica?

**Comment by badernageral** [comment]
Olá, aparentemente é um problema do instalador, vou corrigir. Enquanto isso baixe a versão sem instalador, ela possui o final "all", descompacte e abra o arquivo bgfinancas.jar
Desculpe o incomodo e obrigado por me informar.
________________________________

**Comment by badernageral** [comment]
A verificação de presença do Java foi removida do instalador.
