### ISSUE TITLE
Falha ao executar por falta de lib

### ISSUE THREAD

**Issue by thiagoaag** [badernageral/bgfinancas#26]
Ao tentar utilizar o sistemas pelo pacote executavel **.jar**, ocorreu uma falha por não ter a lib **openjfx** instalada. Como utilizo a distro Manjaro, a solução que encontrei foi instalar a lib:

sudo pacman -S java-openjfx

**Comment by badernageral** [comment]
Olá Thiago, obrigado pelo feedback.
Sobre o openjfx, na README do repositório eu cito ele como dependência em distribuições linux, talvez não ficou muito claro, mas fico feliz que tenha conseguido.
