### ISSUE TITLE
Sugestão sobre Relatórios das Faturas de Cartão

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#27]
Bom dia amigo, tudo bom com você?
Na próxima atualização se possível você poderia incluir em relatórios onde a gente lista as categorias de  despesas por tempo, incluir gráficos por barras verticais mostrando os valores das categorias para a gente ter uma ideia por exemplo das despesas de cada fatura dos cartões mês a mês, do jeito que está dar pra ver mais a gente tem de colocar o mouse em cima da linha para aparecer o valor da fatura.

um grande abraço.

Ass. Abel

**Comment by badernageral** [comment]
Olá @abelmuzy, vou tentar fazer na próxima atualização, mas acredito que não vá ficar legal neste tipo de relatório, pois cada categoria é repetida mês a mês, e o gráfico por barras verticais ocupa muito espaço, se a pessoa escolher um período maior que 5 meses ou muitas categorias, provavelmente as informações irão ficar ilegíveis.

**Comment by badernageral** [comment]
Foi adicionado um relatório de barras verticais na última versão.
https://github.com/badernageral/bgfinancas/releases
