### ISSUE TITLE
Agendar Receitas

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#28]
Bom dia amigo, trago mais uma sugestão, colocar a opção de cadastrar as receitas parceladas como você colocou em despesas, digo isso pois eu estou usando o BG Finanças em parelho com um controle de finanças que fiz no Access, o meu eu coloquei essa opção para não ter o trabalho de cadastrar uma receita de aluguel por exemplo, se tivesse a opção a gente já cadastrava para todos os meses do ano sem ter que cadastrar individual mês a mês.
eu uso o BG em paralelo pois foi feito por um profissional e como eu sou amador o meu pode ter algum bug e me deixar na mão, kkk

um grande abraço.

**Comment by badernageral** [comment]
Olá @abelmuzy, é uma boa ideia, gostei dela, vou implementar, porém não esse mês, estou um pouco ocupado, mas na próxima atualização vou colocar!

**Comment by abelmuzy** [comment]
Que bom que você gostou da ideia, vai ficar bem mais rápido para a gente cadastrar as receitas.

**Comment by badernageral** [comment]
Foi adicionado um agendamento de receitas na última versão.
https://github.com/badernageral/bgfinancas/releases

**Comment by abelmuzy** [comment]
Bom dia amigo td bom com voçê? Eu nao estou conseguindo fazer com que o software de baixa nas cotas quando eu adiciono uma despesa ou de baixa, confere aí pra mim, derrepente estou fazendo algo errado.
voltando ao assunto do saldo em relatorio, quando voçe tiver um tempinho coloca ele nas contas individual tambem, pois assim teremos como saber o saldo mensal de uma conta bancaria por exemplo.
aquele abraço.

**Comment by badernageral** [comment]
Olá @abelmuzy, as cotas estão funcionando bem aqui, você adicionou a cota e depois adicionou as categorias que você quer monitorar a esta cota que você criou? Talvez esse seja o problema.
No extrato, você informa um período e ele pega as despesas e receitas lançados nesse período, quando você filtra por conta, o programa irá exibir somente as receitas e despesas lançadas naquele período para aquela conta, se eu subtrair e exibir um saldo, este saldo não é o saldo da conta naquele dia, mas sim, no período informado no relatório, é o que poderia fazer.

**Comment by abelmuzy** [comment]
Boa noite amigo, entendi, eu me referi ao saldo pois pensei o seguinte: voçe somava as despesas confirmada+despesas aguardando confirmaçao-receita=saldo no periodo selecionado, no caso voçe iria saber quanto entrou e quanto saiu da sua conta e quanto ficou de saldo de um mes por exemplo.

assim fica dificil de fazer?

**Comment by abelmuzy** [comment]
Boa tarde amigo, tudo bom com voçe?
eu tenho 4 cartoes cadastrado no BG com o item mercadopago pois faço compras direto no mercado livre, agora eu adquiri um cartao sem anuidade e fui tentar cadastrar ele igual esta os outros com o item mercadopago nao esta aceitando esta dizendo que ja esta cadastrado, onde voçe acha que eu estou errando pois fiquei uns meses sem usar o BG e posso ter esquecido de algo.

Outra coisa que seria interessante voçe colocar é a soma na tela principal mine relatorio das cotas de despesas e das despesas agendadas para a gente ter uma ideia de quanto podemos gastar, o que voçe acha?

**Comment by badernageral** [comment]
Achei estranho, pois é possível cadastrar cartões com o mesmo nome, tire um print da tela onde está esse erro e poste aqui.
Sobre a sua sugestão, a soma total das cotas é viável fazer, mas a das despesas agendadas, vou remover essa aba, pois é a mesma coisa do planejamento e a soma já é exibida lá.

**Comment by abelmuzy** [comment]
Segue os prints, coloquei uma observaçao na parte inferior de cada print

[Nao aceita cadastrar novo item igual com categoria diferente.docx](https://github.com/badernageral/bgfinancas/files/3119512/Nao.aceita.cadastrar.novo.item.igual.com.categoria.diferente.docx)
(https://github.com/badernageral/bgfinancas/files/3119552/as.despesas.agendadas.seria.bom.voce.deixar.pois.as.faturas.de.cartao.aparece.fechadas.e.em.planejamento.repare.que.elas.aparece.com.as.despesas.individual.docx)

a soma das despesas agendadas seria legal pois a gente ficaria sabendo o total de despesas do mes seguinte ja incluindo as faturas de cartao, certo?
voçe ainda nao tinha observado esse detalhe?
ficou muito bom, derrepente sem querer voçê fez algo excepcional kkk

me ensina como eu faço para acrescentar algo nele pelo netbeans eu consegui abrir ele pelo netbeans mais fiquei meio perdido pois manjo pouco de java.

um grande abraço.

**Comment by badernageral** [comment]
Você falou cartão, mas na verdade é uma despesa. O sistema não deixa cadastrar despesas com o mesmo nome e mesma categoria, mas do jeito que você falou era para funcionar normalmente, tente alterar o nome e veja o que acontece.
Para você conseguir alterar o sistema, você obrigatoriamente vai ter que aprender java, não tem como correr :-(

**Comment by abelmuzy** [comment]
Boa tarde amigo, sim é uma despesa porem feita com cartao de credito, aí eu criei uma categoria fatura de cartao e anexo todos os itens de despesas a ela porem que nem eu te disse, se ja tem um item mercadopago agregado a fatura iraucard visa por exemplo, ele nao esta deixando eu criar outro item mercadopago para fatura itaucard business por exemplo, lembro que antes aceitava por tanto voçe pode ver que tem outras categorias de fatura de cartao com o mesmo item mercadopago, entendeu?
sobre as despesas agendadas eu ficaria muito grato se voçe deixasse, pois do jeito que eu fiz aqui eu consigo ver as faturas fechada do mes seguinte nas despesas agendadas, é só voçe colocar para aparecer a soma dessas despesas agendadas que vai ficar show, pois assim a gente ja vai saber o que nos esperam no mes seguinte.
sobre o software eu ja estou estudando as linhas de codigo java em um curso gratis que achei no youtube, eu so queria saber de voçe como seria o procedimento para eu abrir o BG pelo netbeans para eu tentar mudar alguma coisa, coisa de aprendiz kkk ha nao esquece de colocar a soma nas cotas tambem.
aquele abraço.

**Comment by abelmuzy** [comment]
Bom dia amigo, tive fazendo uns teste aqui e descobrir que colocando os cartoes em cadastro de contas como poupança tem como a gente ver em tempo real quanto esta gastando do limite, depois é só fazer uma transferencia da conta carteira ou bancaria para o cartao que esta vencendo e quitar a fatura.
voçê faz assim tambem? porem só desconta do limite depois que voçe quita a conta, tentei colocar o mesmo nome que esta em contas de cartão mais nao funcionou, seria legal linkar as faturas de cartao com as contas cartao para quando ir agendando despesas ja ir descontando, eu sei que voçe vai falar que é só acessar a aba cartão que ja ver quanto gastou, mais a gente vendo tudo na tele inicial em tempo real é bem melhor.
outra coisa que seria bom, ja que desse jeito fica melhor para avaliar as nossas despesas, seria colocar um filtro nas contas para filtrar as contas individuais e todas ao mesmo tempo.
eu tenho um software chamado Vida Controle Financeiro que tem essa opçao.
outra coisa, porque tem algumas despesas que nao esta descontando das cotas?
conferir aqui esta tudo certinho mais tem umas despesas que nao esta descontando, digo despesas comum, as despesas feita com cartao estao descontando normal.

**Comment by abelmuzy** [comment]
Boa noite amigo, segue o manual do software Vida Controle Financeiro para voçe dá uma olhada sobre o filtro das contas na pagina principal. ele nao tem versao demo
[Manual Vida Controle Financeiro.pdf](https://github.com/badernageral/bgfinancas/files/3125618/Manual.Vida.Controle.Financeiro.pdf)

**Comment by abelmuzy** [comment]
Bom dia amigo, mandei umas mensagens para voçe pela pagina do aplicativo mais aconteceu algo meio estranho, a mensagem nao esta ficando mais na pagina principal assim que eu faço o login, confere aí se chegou pra voçe.
________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: sexta-feira, 26 de abril de 2019 12:48
Para: badernageral/bgfinancas
Cc: abelmuzy; Mention
Assunto: Re: [badernageral/bgfinancas] Agendar Receitas (#28)


Você falou cartão, mas na verdade é uma despesa. O sistema não deixa cadastrar despesas com o mesmo nome e mesma categoria, mas do jeito que você falou era para funcionar normalmente, tente alterar o nome e veja o que acontece.
Para você conseguir alterar o sistema, você obrigatoriamente vai ter que aprender java, não tem como correr :-(

**Comment by badernageral** [comment]
Olá @abelmuzy, esses cartões que você fala são cartões de crédito? porque se forem, deveria cadastrá-los como "cartão de crédito" e definir um limite, conforme você lança as despesas no planejamento, o limite disponível do cartão é atualizado, quando você pagar a fatura do cartão, o limite será retornado. Eu faço desse jeito.
Estou meio sem tempo no momento, mas na próxima atualização vou inserir algumas de suas sugestões.

**Comment by abelmuzy** [comment]
Boa tarde amigo, isso mesmo, se trata de cartao de credito, eu só sugerir colocar eles juntos na tela principal como conta poupança pois voçe ficaria vendo em tempo real descontar do limite quando fizesse ma uma compra, voçe chegou ver o manual do Vida Controle Financeiro, o vida tem essa opçao, sobre as despesas agendadas no mine relatorio eu gostaria que voçe nao tirasse pois da maneira que eu fiz aqui aparece as faturas fechada em mine relatorio e as compras dessa fatura aparece individual no planejamento, voçe chegou ver o print que te mandei?
é só colocar a soma das despesas agendadas e das cotas que ja esta bom demais.
aquele abraço.

**Comment by abelmuzy** [comment]
Olá amigo, estou cadastrando todas as minhas despesas no BG pois é mais confiável do que o meu banco de dados em Access mais continuo observando que as cotas so estao sendo descontadas quando voçe paga fatura de cartao, despesas avulsas nao esta descontando, ja testei fazendo cadastro de despesas diferente tipo: pessoal casa e loja e todas elas nao deu baixa no cota, ver aí pra mim o que pode está acontecendo.

**Comment by abelmuzy** [comment]
interessante, eu importei um backup do ano passado com essa mesma versao 3.71 e esta funcionando as cotas das despesas avulsas normal, o que pode esta acontecendo?

**Comment by badernageral** [comment]
As cotas de despesas se baseiam no mês atual, ou seja, somente despesas lançadas nesse mês descontarão. Você não estaria lançando uma despesa com data de outro mês? Ou você não estaria lançando uma despesa que não pertence a alguma das categorias da cota que você está monitorando? Se não for um desses motivos, não faz sentido não funcionar.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by abelmuzy** [comment]
nao, eu estou cadastrando despesas desse mes e quando dou baixa nao estava descontando da cota.
eu estou refazendo tudo de novo para ver se consigo identificar porque nao estava descontando.
só um pequeno detalhe, quando voçe for fazer a atualizaçao aumenta a janela do mine relatorio para 9 despesas igual esta em contas é só descer os botoes um pouco.

**Comment by abelmuzy** [comment]
Continua nao descontando das cotas, interessante que as despesas de cartao esta descontando normal.

**Comment by badernageral** [comment]
Faca um vídeo demonstrando o procedimento que está fazendo e envie para o meu e-mail, não por aqui, para não ficar público.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by abelmuzy** [comment]
Bom dia amigo, vou tentar kkk acredite nunca fiz um video para YouTube por exemplo, qual o seu e-mail? ou melhor anota o meu ZAP aí pois eu posso ir fazendo pequenos videos e te enviando do jeito que eu fiz os cadastro aqui.
2299843-0242

um grande abraço.
________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: quarta-feira, 22 de maio de 2019 11:13
Para: badernageral/bgfinancas
Cc: abelmuzy; State change
Assunto: Re: [badernageral/bgfinancas] Agendar Receitas (#28)

Faca um vídeo demonstrando o procedimento que está fazendo e envie para o meu e-mail, não por aqui, para não ficar público.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by badernageral** [comment]
Mande nesse e-mail: jrma@uft.edu.br

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by abelmuzy** [comment]
Abel Muzy compartilhou um arquivo do OneDrive com você. Para exibi-lo, clique no link abaixo.
<https://1drv.ms/u/s!AtGeyezOJyJEwaALHkF5QNW179a0SA>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AtGeyezOJyJEwaALHkF5QNW179a0SA>
Meu Primeiro Video_19-05-25_23.13.40.wmv 1.7z<https://1drv.ms/u/s!AtGeyezOJyJEwaALHkF5QNW179a0SA>

Bom dia amigo, td bom?
consegui improvisar um video aqui.
eu disse no video que deveria ser o itens que eu coloquei o nome diferente do que esta em cotas mais nao é pois coloquei igual esta em cotas e continua nao descontando as cotas.
esta compactado com o software 7zip
________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: sexta-feira, 24 de maio de 2019 15:23
Para: badernageral/bgfinancas
Cc: abelmuzy; State change
Assunto: Re: [badernageral/bgfinancas] Agendar Receitas (#28)

Mande nesse e-mail: jrma@uft.edu.br

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by abelmuzy** [comment]
ufa! Matei a charada, o que estava acontecendo!
eu estava colocando categorias discriminadas dentro das cotas, por isso nao estava dando certo.
como eu descobri: analisei o porque as faturas estava dando certo e as outras despesas nao, foi só eu analisar o seguinte:
se a cota despesas de cartao pessoal estava so com o nome das faturas entao eu deduzi que as cotas de despesas da loja por exemplo teria de esta só despesa da loja dentro da categoria cotas, entao eu fiz isso inclui despesa da loja em categoria de cotas e apaguei as despesas que estava discriminadas e foi batata, descontou na hora.

agora é só voçe colocar a soma delas em mine relatorios, me refiro a soma total de cotas e das despesas agendadas que voçe falou que iria retirar e eu falei para deixar pois do jeito que eu fiz aqui daria para eu ir vendo as proximas faturas fechada que estao para vencer pois em planejamento mostra mais mostra item a item nao mostra as faturas fechada, entendeu?
desculpa eu te dar esse trabalho todo pois a gente que tem comercio a cabeça fica a mil por hora, kkk
um grande abraço.
________________________________
De: José Robson Mariano Alves <notifications@github.com>
Enviado: sexta-feira, 24 de maio de 2019 15:23
Para: badernageral/bgfinancas
Cc: abelmuzy; State change
Assunto: Re: [badernageral/bgfinancas] Agendar Receitas (#28)

Mande nesse e-mail: jrma@uft.edu.br

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by badernageral** [comment]
Olá @abelmuzy, fui ver hoje, ia te responder, mas vejo que já achou o erro.
Você estava adicionando uma despesa de uma categoria que não estava adicionada na cota desejada, bastava adicionar a categoria na cota que iria funcionar.
