### ISSUE TITLE
Relatório de Extrato incluir o campo saldo

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#29]
Bom dia amigo, mais uma dica importante para voçe incluir no BG quando voçe for colocar o campo para agendar Receitas, é no campo relatório de extrato voçe incluir o campo saldo para por exemplo quando a gente quiser saber o saldo do mês e do ano de uma determinada conta de banco por exemplo.

um grande abraço.

**Comment by badernageral** [comment]
Olá @abelmuzy, liberei a versão 3.7 que implementa várias das sugestões que você pediu, menos essa, pois o programa não mantém um histórico do saldo das contas.

**Comment by abelmuzy** [comment]
Boa noite amigo, Entendo, mais nao teria como colocar o saldo somando as despesas realizadas+despesas agendadas menos receita, pois assim a gente iria saber quanto teria de saldo num geral.

**Comment by abelmuzy** [comment]
Bom dia amigo, analisando o software aqui, percebi que o filtro de receita em relatório não esta funcionando, confere aí.

Voltando ao assunto sobre o saldo, seria muito bom se você conseguisse incluir para a gente ter uma ideia geral do que já gastou e o que esta pendente durante o ano.

Aquele abraço.
