### ISSUE TITLE
Relatorio nao tem o campo saldo

### ISSUE THREAD

**Issue by abelmuzy** [badernageral/bgfinancas#30]
Boa noite amigo, ficou muito bom as atualizações, você só esqueceu do campo saldo no extrato de relatório, tipo despesas efetuadas+despesas agendadas-receitas para a gente ter uma ideia no geral sem precisar fazer conta na calculadora.

**Comment by badernageral** [comment]
Olá @abelmuzy, soltei uma nova versão do sistema corrigindo alguns bugs da anterior e acabei colocando o saldo, porém não é o saldo individual de cada conta, mas sim o saldo geral do período informado.
Veja [aqui](https://github.com/badernageral/bgfinancas/releases) a lista de alterações.

**Comment by abelmuzy** [comment]
Bom dia amigo, ficou muito bom, agora a hora que voçe tiver um tempinho ver se consegue colocar o saldo do campo relatorio para as contas individual, tipo listar banco itau aparecer o dinheiro que entra o que sai e o saldo do mes para a gente ter uma ideia da nossa movimentaçao bancaria para ver se esta batendo tudo certinho.

um grande abraço.
